package Nabytok.Enums;

public enum OrderStateValues {
    WAITING_IN_QUEUE_1,
    PROCESSING_PREPARING,
    WAITING_IN_QUEUE_2,
    PROCESSING_COLORING,
    WAITING_IN_QUEUE_3,
    PROCESSING_COMPUTING,
    PROCESSING_FITTINGS,
    ORDER_DONE
}
